---

- name: Install infra-agent yum
  environment: "{{ env_vars }}"
  yum:
    name: "{{ package_name }}"
    update_cache: yes
  retries: 5
  delay: 60
  when: not "python3" in ansible_python_interpreter

- name: Install infra-agent dnf
  environment: "{{ env_vars }}"
  dnf:
    name: "{{ package_name }}"
    update_cache: yes
  retries: 5
  delay: 60
  when: "'python3' in ansible_python_interpreter"

...
