configurationDefinitions:
  - platform: HOST
    description: infrastructure agent configuration 
    type: infrastructure-config
    version: 1.0.0
    format: yml
    operatingSystem: WINDOWS
  - platform: HOST
    description: infrastructure agent configuration 
    type: infrastructure-config
    version: 1.0.0
    format: yml
    operatingSystem: LINUX
  - platform: KUBERNETESCLUSTER
    description: infrastructure agent configuration 
    type: infrastructure-config
    version: 1.0.0
    format: yml
    operatingSystem: LINUX
