name: . ğŸ¤ A2Q Canaries

run-name: ${{ github.actor }} is setting up canaries for A2Q ğŸš€
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to test'
        required: true
      linux:
        description: 'ğŸ§ Should create canaries for Linux?'
        type: boolean
        default: true
        required: false
      windows:
        description: 'ğŸªŸ Should create canaries for Windows?'
        type: boolean
        default: true
        required: false

jobs:

  A2Q-canaries-linux:
    if: ${{ github.event.inputs.linux == 'true' }}
    uses: ./.github/workflows/component_canaries.yml
    with:
      PLATFORM: "linux"
      TAG: ${{ github.event.inputs.tag }}
      A2Q: true
    secrets:
      AWS_VPC_SUBNET: ${{secrets.AWS_VPC_SUBNET}}
