name: . ðŸ”ðŸ” Show N files added before and after datetime into the S3 repository

on:
  workflow_dispatch:
    inputs:
      count:
        description: 'Number of files to show'
        type: string
        default: '500'
        required: true
      date_time:
        description: 'UTC Date and time to show files added before and after (YYYY-MM-DD HH:MM:SS)'
        type: string
        required: true

jobs:
  list-files:
    name: List files added before and after datetime
    runs-on: ubuntu-20.04
    steps:
      - name: Validate datetime
        run: |
          datetime="${{ github.event.inputs.date_time }}"
          # Regular expression to match the format YYYY-MM-DD HH:MM:SS
          regex="^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$"
      
          if [[ $datetime =~ $regex ]]; then
            # Use date command to check if it's a valid date
            date -d "$datetime" >/dev/null 2>&1 || exit 1
          else
            exit 1
          fi

      - name: List files created before and after datetime in S3
        run: |
          TZ="UTC" aws s3 ls s3://nr-downloads-main/infrastructure_agent/ --recursive | sort | grep --color  -m 1 -C {{ github.event.inputs.count }} "^${{ github.event.inputs.date_time }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.OHAI_AWS_ACCESS_KEY_ID_PRODUCTION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.OHAI_AWS_SECRET_ACCESS_KEY_PRODUCTION }}
          AWS_ROLE_ARN: ${{ secrets.OHAI_AWS_ROLE_ARN_PRODUCTION }}
          AWS_ROLE_SESSION_NAME: ${{ secrets.OHAI_AWS_ROLE_SESSION_NAME_PRODUCTION }}
